port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - {name: 8元老牌专线机场：cczzuu.top, server: 47.239.6.251, port: 13779, type: vless, uuid: 928e6cce-8ced-4243-9a48-a6642edd09b0, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg, short-id: af1bdd293097b664}, servername: tesla.com, client-fingerprint: chrome, network: raw, udp: true}
  - {name: "🇨🇳 中国_B56JSS", server: 103.210.161.8, port: 1080, type: socks5, udp: true, username: T2c9PTpPZz09, password: T2c9PTpPZz09}
  - {name: "🇭🇰 香港_UVUCA4", server: 47.238.210.5, port: 13779, type: vless, uuid: 928e6cce-8ced-4243-9a48-a6642edd09b0, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg, short-id: af1bdd293097b664}, servername: tesla.com, client-fingerprint: chrome, network: raw, udp: true}
  - {name: "🇺🇸 美国_4BSVC9", server: 179.254.94.102, port: 44444, type: vless, uuid: ae2368cc-0fbe-4a06-a23e-fb73a4ac025a, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: LZnkyLxA8cYoDAsmxGh0lOr1-auyZI5t_LSU-FNBkSs, short-id: ""}, servername: www.iij.ad.jp, client-fingerprint: firefox, network: tcp, udp: true}
  - {name: "🇺🇸 美国_GAW1TT", server: 198.46.215.223, port: 8443, type: vless, uuid: 6346ee2b-aefa-4a58-963a-bb851ed08f41, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: L817rvnreaFtFfcqfOizxgY7ZzFeSdtopH9HVrB56hk, short-id: 0b3bf761ca812ee9}, servername: www.intel.com, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇩🇪 德国_DFP8JN", server: 31.76.100.41, port: 443, type: vless, uuid: d72f05b0-b182-4783-a6f2-21cecc7d841a, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: SibLV5WBGdljTiUCmKx77KhHQfErCwjDMD_ZLoha3js, short-id: a1b2c3d4e5f67890}, servername: dzen.ru, client-fingerprint: firefox, network: tcp, udp: true}
  - {name: "🇧🇬 保加利亚_B3X424", server: 45.9.156.24, port: 443, type: vless, uuid: 2f35965a-9a9b-45fd-ba32-987296dfb6be, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: 0f0dh_FUju5cHgQcIwUjHvxQb9aIZ00p0kZRHeE7Ey4, short-id: 501ab3325b77e1ca}, servername: bg2.univesalsrv.com, client-fingerprint: chrome, network: grpc, grpc-opts: {grpc-service-name: api.v2.PushService}, udp: true}
  - {name: "🇫🇮 芬兰_C2MFWG", server: c5b47b423412e973.fn-1.globalmymusic.com, port: 443, type: vless, uuid: fcc64e6f-bdcd-471a-a2d4-27c757578070, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: lsDSttIgw1roTVhNzcliywH74lXtRShbmMOoxUjQtkw, short-id: b684d13617792bb2}, servername: nr6.nl, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇬🇧 英国_GPUA1F", server: 194.150.166.229, port: 9443, type: vless, uuid: ff6d2dda-7b90-404e-9951-34b3124bfdfa, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: M6Ck7wUfOLhQl4582CBnaXwscPEP6SCpdEkUDzoj4Fc, short-id: ad20d2ba}, servername: storage.yandexcloud.net, client-fingerprint: safari, network: tcp, udp: true}
  - {name: "🇺🇸 美国_PJQD7I", server: 108.59.244.158, port: 443, type: vless, uuid: b05c7ba3-c5b1-4b6f-a599-eaaf3019d94c, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: 9PK8Akff36jRpeEWGIyCvBMBpM45CZshy8D4rgxZCAc, short-id: fff2225187c77daf}, servername: ads.x5.ru, client-fingerprint: qq, network: tcp, udp: true}
  - {name: "🇩🇪 德国_CQWGS0", server: 77.91.76.156, port: 57160, type: vless, uuid: 68ad9a6d-2463-4c31-92a7-31547b9d4783, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: Tbu7sr_pvHngDWFIa0ApL5UL9vEGxlHESd9g53KQehw, short-id: 77b5}, servername: funpay.com, client-fingerprint: firefox, network: raw, udp: true}
  - {name: "🇩🇪 德国_D1DYIH", server: 217.19.122.17, port: 10654, type: vless, uuid: 953358cb-82ba-4296-960d-6d2ec3468f4c, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: ds10ztOlMn8xfeIKEQ1m3I-tdem-abZbHKtJCU13CQM, short-id: 5c3fb122}, servername: bl3fk52.sysopnova.art, client-fingerprint: firefox, network: xhttp, udp: true}
  - {name: "🇵🇱 波兰_55E4XY", server: 194.93.63.246, port: 443, type: vless, uuid: c5694dc5-39fd-4a92-8430-3837baa522a3, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: GmZv3anSeAeHr_cMFKr-6MPLli-nyKNatnY6P3AFK00, short-id: 9c2378562188c3cb}, servername: pl.bubahero.com, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇺🇸 美国_I0076O", server: lyra.yokkastars.com, port: 40443, type: vless, uuid: 5be7fb02-b6a5-450f-b041-3243b98e8420, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: Uvj5H9pDJP0HX2bN7NN7sCQwVCrC5N2NbKf-yuy1ikE, short-id: ee33}, servername: deepl.com, client-fingerprint: edge, network: tcp, udp: true}
  - {name: "🇷🇺 俄罗斯_GZ4ASD", server: 195.133.23.200, port: 10081, type: ss, udp: true, cipher: aes-256-gcm, password: 81a20429165df87e}
  - {name: "🇫🇮 芬兰_1E7KR5", server: 31.76.53.246, port: 443, type: vless, uuid: 61da8f4b-6ab1-4ca7-bae0-1cec4f9be2f8, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: HhEhP1K1hj4tUSqlBNIroSqc5zfT_xK3DCvzQ5xOsBQ, short-id: 006fd6dfc38adf33}, servername: cdnjs.cloudflare.com, client-fingerprint: safari, network: tcp, udp: true}
  - {name: "🇳🇱 荷兰_K6A4ZE", server: 217.60.23.218, port: 443, type: vless, uuid: 0f11b72f-1af1-4f0a-b992-87a8241d9213, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: uAoKx_ePWGe_jowwFZt7x3oZSNU3VJl9dIQmeYG22FM, short-id: 9a4d61e8c2f735b0}, servername: www.bing.com, client-fingerprint: firefox, network: tcp, udp: true}
  - {name: "🇷🇸 塞尔维亚_8G49JA", server: 150.40.126.19, port: 443, type: vless, uuid: 2f35965a-9a9b-45fd-ba32-987296dfb6be, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: tL16MVY08r-7YDXb1_gxuBBWInpSFp97ZLJ_ax3R2iE, short-id: 1469af2040b7c323}, servername: rs2.univesalsrv.com, client-fingerprint: firefox, network: grpc, grpc-opts: {grpc-service-name: media.v1.ObjectService}, udp: true}
  - {name: "🇺🇸 美国_IS6UF9", server: 136.117.218.86, port: 443, type: vless, uuid: dffab367-7769-4c6c-86f2-66fc6bd03003, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: LYnDDS0AkBwVeeTyIEE5MhrTV_PZO5f1qBAbMN6z4HM, short-id: f1955f72763eb2fb}, servername: www.cloudflare.com, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇷🇸 塞尔维亚_8ICD4D", server: 150.40.126.21, port: 443, type: vless, uuid: 2f35965a-9a9b-45fd-ba32-987296dfb6be, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: gHDoSWGWMVZKWNKONWHw-Cpl0-bdI6GaKusgJIQ-vWQ, short-id: 35d05b666e2c6cdf}, servername: rs3.univesalsrv.com, client-fingerprint: firefox, network: grpc, grpc-opts: {grpc-service-name: edge.v2.FeedService}, udp: true}
  - {name: "🇫🇮 芬兰_72QCC9", server: 31.76.245.63, port: 443, type: vless, uuid: d72f05b0-b182-4783-a6f2-21cecc7d841a, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: SibLV5WBGdljTiUCmKx77KhHQfErCwjDMD_ZLoha3js, short-id: a1b2c3d4e5f67890}, servername: dzen.ru, client-fingerprint: firefox, network: tcp, udp: true}
  - {name: "🇫🇮 芬兰_K153X8", server: p1tun4.greewebservices.ir, port: 1080, type: ss, udp: true, cipher: chacha20-ietf-poly1305, password: LMnotcv4RdaEOBXT-LdtfA}
  - {name: "🇩🇪 德国_T3GISM", server: down.chaqalli.com, port: 2082, type: vless, uuid: 560ecca1-7e20-4b41-b4d6-781fb3bc179d, tls: false, tfo: false, skip-cert-verify: false, network: ws, ws-opts: {path: /, headers: {Host: down.chaqalli.com}}, udp: true}
  - {name: "🇵🇱 波兰_DSG9G8", server: 94.183.209.243, port: 8443, type: vless, uuid: 7ab9fe4f-6699-427f-a828-9fcf2496d714, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: GYGRmooJbciRJqgRyAhyuY4taALwvAGNN721zIKA4g0, short-id: d2f6787eda1b6fa0}, servername: www.cloudflare.com, client-fingerprint: firefox, network: grpc, grpc-opts: {grpc-service-name: a8a08a507c}, udp: true}
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - "♻️ 自动选择"
      - DIRECT
      - 8元老牌专线机场：cczzuu.top
      - "🇨🇳 中国_B56JSS"
      - "🇭🇰 香港_UVUCA4"
      - "🇺🇸 美国_4BSVC9"
      - "🇺🇸 美国_GAW1TT"
      - "🇩🇪 德国_DFP8JN"
      - "🇧🇬 保加利亚_B3X424"
      - "🇫🇮 芬兰_C2MFWG"
      - "🇬🇧 英国_GPUA1F"
      - "🇺🇸 美国_PJQD7I"
      - "🇩🇪 德国_CQWGS0"
      - "🇩🇪 德国_D1DYIH"
      - "🇵🇱 波兰_55E4XY"
      - "🇺🇸 美国_I0076O"
      - "🇷🇺 俄罗斯_GZ4ASD"
      - "🇫🇮 芬兰_1E7KR5"
      - "🇳🇱 荷兰_K6A4ZE"
      - "🇷🇸 塞尔维亚_8G49JA"
      - "🇺🇸 美国_IS6UF9"
      - "🇷🇸 塞尔维亚_8ICD4D"
      - "🇫🇮 芬兰_72QCC9"
      - "🇫🇮 芬兰_K153X8"
      - "🇩🇪 德国_T3GISM"
      - "🇵🇱 波兰_DSG9G8"
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 8元老牌专线机场：cczzuu.top
      - "🇨🇳 中国_B56JSS"
      - "🇭🇰 香港_UVUCA4"
      - "🇺🇸 美国_4BSVC9"
      - "🇺🇸 美国_GAW1TT"
      - "🇩🇪 德国_DFP8JN"
      - "🇧🇬 保加利亚_B3X424"
      - "🇫🇮 芬兰_C2MFWG"
      - "🇬🇧 英国_GPUA1F"
      - "🇺🇸 美国_PJQD7I"
      - "🇩🇪 德国_CQWGS0"
      - "🇩🇪 德国_D1DYIH"
      - "🇵🇱 波兰_55E4XY"
      - "🇺🇸 美国_I0076O"
      - "🇷🇺 俄罗斯_GZ4ASD"
      - "🇫🇮 芬兰_1E7KR5"
      - "🇳🇱 荷兰_K6A4ZE"
      - "🇷🇸 塞尔维亚_8G49JA"
      - "🇺🇸 美国_IS6UF9"
      - "🇷🇸 塞尔维亚_8ICD4D"
      - "🇫🇮 芬兰_72QCC9"
      - "🇫🇮 芬兰_K153X8"
      - "🇩🇪 德国_T3GISM"
      - "🇵🇱 波兰_DSG9G8"
  - name: 🌍 国外媒体
    type: select
    proxies:
      - "🚀 节点选择"
      - "♻️ 自动选择"
      - "🎯 全球直连"
      - 8元老牌专线机场：cczzuu.top
      - "🇨🇳 中国_B56JSS"
      - "🇭🇰 香港_UVUCA4"
      - "🇺🇸 美国_4BSVC9"
      - "🇺🇸 美国_GAW1TT"
      - "🇩🇪 德国_DFP8JN"
      - "🇧🇬 保加利亚_B3X424"
      - "🇫🇮 芬兰_C2MFWG"
      - "🇬🇧 英国_GPUA1F"
      - "🇺🇸 美国_PJQD7I"
      - "🇩🇪 德国_CQWGS0"
      - "🇩🇪 德国_D1DYIH"
      - "🇵🇱 波兰_55E4XY"
      - "🇺🇸 美国_I0076O"
      - "🇷🇺 俄罗斯_GZ4ASD"
      - "🇫🇮 芬兰_1E7KR5"
      - "🇳🇱 荷兰_K6A4ZE"
      - "🇷🇸 塞尔维亚_8G49JA"
      - "🇺🇸 美国_IS6UF9"
      - "🇷🇸 塞尔维亚_8ICD4D"
      - "🇫🇮 芬兰_72QCC9"
      - "🇫🇮 芬兰_K153X8"
      - "🇩🇪 德国_T3GISM"
      - "🇵🇱 波兰_DSG9G8"
  - name: 📲 电报信息
    type: select
    proxies:
      - "🚀 节点选择"
      - "🎯 全球直连"
      - 8元老牌专线机场：cczzuu.top
      - "🇨🇳 中国_B56JSS"
      - "🇭🇰 香港_UVUCA4"
      - "🇺🇸 美国_4BSVC9"
      - "🇺🇸 美国_GAW1TT"
      - "🇩🇪 德国_DFP8JN"
      - "🇧🇬 保加利亚_B3X424"
      - "🇫🇮 芬兰_C2MFWG"
      - "🇬🇧 英国_GPUA1F"
      - "🇺🇸 美国_PJQD7I"
      - "🇩🇪 德国_CQWGS0"
      - "🇩🇪 德国_D1DYIH"
      - "🇵🇱 波兰_55E4XY"
      - "🇺🇸 美国_I0076O"
      - "🇷🇺 俄罗斯_GZ4ASD"
      - "🇫🇮 芬兰_1E7KR5"
      - "🇳🇱 荷兰_K6A4ZE"
      - "🇷🇸 塞尔维亚_8G49JA"
      - "🇺🇸 美国_IS6UF9"
      - "🇷🇸 塞尔维亚_8ICD4D"
      - "🇫🇮 芬兰_72QCC9"
      - "🇫🇮 芬兰_K153X8"
      - "🇩🇪 德国_T3GISM"
      - "🇵🇱 波兰_DSG9G8"
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - "🎯 全球直连"
      - "🚀 节点选择"
      - 8元老牌专线机场：cczzuu.top
      - "🇨🇳 中国_B56JSS"
      - "🇭🇰 香港_UVUCA4"
      - "🇺🇸 美国_4BSVC9"
      - "🇺🇸 美国_GAW1TT"
      - "🇩🇪 德国_DFP8JN"
      - "🇧🇬 保加利亚_B3X424"
      - "🇫🇮 芬兰_C2MFWG"
      - "🇬🇧 英国_GPUA1F"
      - "🇺🇸 美国_PJQD7I"
      - "🇩🇪 德国_CQWGS0"
      - "🇩🇪 德国_D1DYIH"
      - "🇵🇱 波兰_55E4XY"
      - "🇺🇸 美国_I0076O"
      - "🇷🇺 俄罗斯_GZ4ASD"
      - "🇫🇮 芬兰_1E7KR5"
      - "🇳🇱 荷兰_K6A4ZE"
      - "🇷🇸 塞尔维亚_8G49JA"
      - "🇺🇸 美国_IS6UF9"
      - "🇷🇸 塞尔维亚_8ICD4D"
      - "🇫🇮 芬兰_72QCC9"
      - "🇫🇮 芬兰_K153X8"
      - "🇩🇪 德国_T3GISM"
      - "🇵🇱 波兰_DSG9G8"
  - name: 🍎 苹果服务
    type: select
    proxies:
      - "🚀 节点选择"
      - "🎯 全球直连"
      - 8元老牌专线机场：cczzuu.top
      - "🇨🇳 中国_B56JSS"
      - "🇭🇰 香港_UVUCA4"
      - "🇺🇸 美国_4BSVC9"
      - "🇺🇸 美国_GAW1TT"
      - "🇩🇪 德国_DFP8JN"
      - "🇧🇬 保加利亚_B3X424"
      - "🇫🇮 芬兰_C2MFWG"
      - "🇬🇧 英国_GPUA1F"
      - "🇺🇸 美国_PJQD7I"
      - "🇩🇪 德国_CQWGS0"
      - "🇩🇪 德国_D1DYIH"
      - "🇵🇱 波兰_55E4XY"
      - "🇺🇸 美国_I0076O"
      - "🇷🇺 俄罗斯_GZ4ASD"
      - "🇫🇮 芬兰_1E7KR5"
      - "🇳🇱 荷兰_K6A4ZE"
      - "🇷🇸 塞尔维亚_8G49JA"
      - "🇺🇸 美国_IS6UF9"
      - "🇷🇸 塞尔维亚_8ICD4D"
      - "🇫🇮 芬兰_72QCC9"
      - "🇫🇮 芬兰_K153X8"
      - "🇩🇪 德国_T3GISM"
      - "🇵🇱 波兰_DSG9G8"
  - name: 📢 谷歌FCM
    type: select
    proxies:
      - "🚀 节点选择"
      - "🎯 全球直连"
      - "♻️ 自动选择"
      - 8元老牌专线机场：cczzuu.top
      - "🇨🇳 中国_B56JSS"
      - "🇭🇰 香港_UVUCA4"
      - "🇺🇸 美国_4BSVC9"
      - "🇺🇸 美国_GAW1TT"
      - "🇩🇪 德国_DFP8JN"
      - "🇧🇬 保加利亚_B3X424"
      - "🇫🇮 芬兰_C2MFWG"
      - "🇬🇧 英国_GPUA1F"
      - "🇺🇸 美国_PJQD7I"
      - "🇩🇪 德国_CQWGS0"
      - "🇩🇪 德国_D1DYIH"
      - "🇵🇱 波兰_55E4XY"
      - "🇺🇸 美国_I0076O"
      - "🇷🇺 俄罗斯_GZ4ASD"
      - "🇫🇮 芬兰_1E7KR5"
      - "🇳🇱 荷兰_K6A4ZE"
      - "🇷🇸 塞尔维亚_8G49JA"
      - "🇺🇸 美国_IS6UF9"
      - "🇷🇸 塞尔维亚_8ICD4D"
      - "🇫🇮 芬兰_72QCC9"
      - "🇫🇮 芬兰_K153X8"
      - "🇩🇪 德国_T3GISM"
      - "🇵🇱 波兰_DSG9G8"
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - "🚀 节点选择"
      - "♻️ 自动选择"
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - "🚀 节点选择"
      - "🎯 全球直连"
      - "♻️ 自动选择"
      - 8元老牌专线机场：cczzuu.top
      - "🇨🇳 中国_B56JSS"
      - "🇭🇰 香港_UVUCA4"
      - "🇺🇸 美国_4BSVC9"
      - "🇺🇸 美国_GAW1TT"
      - "🇩🇪 德国_DFP8JN"
      - "🇧🇬 保加利亚_B3X424"
      - "🇫🇮 芬兰_C2MFWG"
      - "🇬🇧 英国_GPUA1F"
      - "🇺🇸 美国_PJQD7I"
      - "🇩🇪 德国_CQWGS0"
      - "🇩🇪 德国_D1DYIH"
      - "🇵🇱 波兰_55E4XY"
      - "🇺🇸 美国_I0076O"
      - "🇷🇺 俄罗斯_GZ4ASD"
      - "🇫🇮 芬兰_1E7KR5"
      - "🇳🇱 荷兰_K6A4ZE"
      - "🇷🇸 塞尔维亚_8G49JA"
      - "🇺🇸 美国_IS6UF9"
      - "🇷🇸 塞尔维亚_8ICD4D"
      - "🇫🇮 芬兰_72QCC9"
      - "🇫🇮 芬兰_K153X8"
      - "🇩🇪 德国_T3GISM"
      - "🇵🇱 波兰_DSG9G8"

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,🚀 节点选择
  - RULE-SET,proxy,🚀 节点选择
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,🚀 节点选择
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🚀 节点选择
