port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
  - {name: 8元老牌专线机场：cczzuu.top, server: 47.238.210.5, port: 13779, type: vless, uuid: 928e6cce-8ced-4243-9a48-a6642edd09b0, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg, short-id: af1bdd293097b664}, servername: tesla.com, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇭🇰 香港_VU7BAQ", server: 47.239.6.251, port: 13779, type: vless, uuid: 928e6cce-8ced-4243-9a48-a6642edd09b0, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: llTyp52oRXnJmQ3I9UUrmlwbMA79B-wLCRHCu-8dLGg, short-id: af1bdd293097b664}, servername: tesla.com, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇨🇳 中国_PF5FOH", server: 103.210.161.8, port: 1080, type: socks5, udp: true, username: Og, password: Og}
  - {name: "🇹🇼 台湾_9SG9SN", server: 35.201.181.122, port: 443, type: vless, uuid: 22a0b0bd-1cd0-43fa-a7c3-73b24eae44e2, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: PLslPQOBA3bfWO5hXLv7jioCTuNR8vCxa_axi0dC7C0, short-id: 32f66f37df3f58d2}, servername: www.cloudflare.com, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇺🇸 美国_M9WO69", server: jp.sofast.live, port: 52683, type: vless, uuid: 399b6b23-cc40-4831-a494-61948e2df133, tls: false, tfo: false, skip-cert-verify: false, network: tcp, udp: true}
  - {name: "🇷🇴 罗马尼亚_A4MJMP", server: 193.163.203.253, port: 443, type: vless, uuid: 441afe11-a180-4516-bb80-80a8a6b38705, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: gE8LUmGFXik94SoDXNiAG5KprGyhjoRwDuhGebgAVWk, short-id: 5ee019e02e6ed99a}, servername: yandex.ru, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇩🇪 德国_YAH87O", server: 31.76.101.39, port: 443, type: vless, uuid: d72f05b0-b182-4783-a6f2-21cecc7d841a, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: SibLV5WBGdljTiUCmKx77KhHQfErCwjDMD_ZLoha3js, short-id: a1b2c3d4e5f67890}, servername: dzen.ru, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇮🇩 印尼_CTBG80", server: 103.172.197.2, port: 29172, type: vless, uuid: 3977434d-6a9b-4858-8ced-80326ba5e367, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: pff94OJwuKXnF7_3SJ8KKJuAN4GJtInBlR-kg-4mwzQ, short-id: ""}, servername: aws.amazon.com, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇳🇱 荷兰_1O3UBK", server: 94.237.40.197, port: 443, type: vless, uuid: e96896d8-72d1-496f-8d28-b3fa0de4a562, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: RYfzci_ctBzEbBah0jwygnWrGer9_LQfjOgmh9VizQE, short-id: f9}, servername: bazitory.com, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇫🇷 法国_ALKKR7", server: 113.30.154.65, port: 443, type: vless, uuid: 550a69ec-fec1-4eca-b939-4ee076875fa8, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc, short-id: ""}, servername: sellflow.org, client-fingerprint: firefox, network: tcp, udp: true}
  - {name: "🇱🇻 拉脱维亚_QFC71C", server: 195.123.212.60, port: 15392, type: vless, uuid: de78ba38-5600-47d1-b93b-b45bdf280ac0, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: TgaE-83sqLrJ6auwPP2Nq7vDO_xuFqa6uMnG4Au18jg, short-id: "82"}, servername: intel.com, client-fingerprint: firefox, network: tcp, udp: true}
  - {name: "🇲🇩 摩尔多瓦_JS7XT7", server: 89.35.14.32, port: 443, type: vless, uuid: 2f35965a-9a9b-45fd-ba32-987296dfb6be, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: q38CddDj2g-XNDc0uW1m6S6b8iGY_Bne2RwX7C_FYCQ, short-id: 9a72d40f1ff882b3}, servername: md3.univesalsrv.com, client-fingerprint: chrome, network: grpc, grpc-opts: {grpc-service-name: stats.v2.PushService}, udp: true}
  - {name: "🇧🇬 保加利亚_88LFF7", server: 45.9.156.24, port: 443, type: vless, uuid: 2f35965a-9a9b-45fd-ba32-987296dfb6be, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: 0f0dh_FUju5cHgQcIwUjHvxQb9aIZ00p0kZRHeE7Ey4, short-id: 501ab3325b77e1ca}, servername: bg2.univesalsrv.com, client-fingerprint: chrome, network: grpc, grpc-opts: {grpc-service-name: api.v2.PushService}, udp: true}
  - {name: "🇷🇸 塞尔维亚_6XQRNL", server: 150.40.126.19, port: 443, type: vless, uuid: 2f35965a-9a9b-45fd-ba32-987296dfb6be, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: tL16MVY08r-7YDXb1_gxuBBWInpSFp97ZLJ_ax3R2iE, short-id: 1469af2040b7c323}, servername: rs2.univesalsrv.com, client-fingerprint: firefox, network: grpc, grpc-opts: {grpc-service-name: media.v1.ObjectService}, udp: true}
  - {name: "🇬🇧 英国_P3HTT7", server: 213.178.141.33, port: 443, type: vless, uuid: d0f0a880-0df1-48c9-bdf1-5669fb9483ce, tls: true, tfo: false, flow: xtls-rprx-vision, skip-cert-verify: false, reality-opts: {public-key: SB1uC0OEveYjSiS_Nuw9Ld-uVVXWqi794OGnldthY3I, short-id: ""}, servername: germa12.ggisopi.su, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇨🇦 加拿大_5GRYV7", server: 34.95.28.161, port: 443, type: vless, uuid: 448b76ac-c636-4303-bec1-0b2c22afee0c, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: l4tGdE5Zn8ABfBQns3pRBcxy6CckHTLSIsw5JaBumTk, short-id: c9d4bf8d94ec8dab}, servername: www.cloudflare.com, client-fingerprint: chrome, network: tcp, udp: true}
  - {name: "🇸🇪 瑞典_TF5CKT", server: 171.25.158.95, port: 1080, type: socks5, udp: true, username: Og==, password: Og==}
  - {name: "🇰🇿 哈萨克斯坦_2GL0D7", server: 83.222.23.81, port: 38065, type: vless, uuid: 4b9063e0-3288-44e9-9aac-80fbfce323a0, tls: true, tfo: false, skip-cert-verify: false, reality-opts: {public-key: dSSDPTK6AHfAdRAXD9i4rzqcNIY65RxlF25UyCKdiyo, short-id: fa}, servername: yahoo.com, client-fingerprint: chrome, network: raw, udp: true}
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - "♻️ 自动选择"
      - DIRECT
      - 8元老牌专线机场：cczzuu.top
      - "🇭🇰 香港_VU7BAQ"
      - "🇨🇳 中国_PF5FOH"
      - "🇹🇼 台湾_9SG9SN"
      - "🇺🇸 美国_M9WO69"
      - "🇷🇴 罗马尼亚_A4MJMP"
      - "🇩🇪 德国_YAH87O"
      - "🇮🇩 印尼_CTBG80"
      - "🇳🇱 荷兰_1O3UBK"
      - "🇫🇷 法国_ALKKR7"
      - "🇱🇻 拉脱维亚_QFC71C"
      - "🇲🇩 摩尔多瓦_JS7XT7"
      - "🇧🇬 保加利亚_88LFF7"
      - "🇷🇸 塞尔维亚_6XQRNL"
      - "🇬🇧 英国_P3HTT7"
      - "🇨🇦 加拿大_5GRYV7"
      - "🇸🇪 瑞典_TF5CKT"
      - "🇰🇿 哈萨克斯坦_2GL0D7"
  - name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 8元老牌专线机场：cczzuu.top
      - "🇭🇰 香港_VU7BAQ"
      - "🇨🇳 中国_PF5FOH"
      - "🇹🇼 台湾_9SG9SN"
      - "🇺🇸 美国_M9WO69"
      - "🇷🇴 罗马尼亚_A4MJMP"
      - "🇩🇪 德国_YAH87O"
      - "🇮🇩 印尼_CTBG80"
      - "🇳🇱 荷兰_1O3UBK"
      - "🇫🇷 法国_ALKKR7"
      - "🇱🇻 拉脱维亚_QFC71C"
      - "🇲🇩 摩尔多瓦_JS7XT7"
      - "🇧🇬 保加利亚_88LFF7"
      - "🇷🇸 塞尔维亚_6XQRNL"
      - "🇬🇧 英国_P3HTT7"
      - "🇨🇦 加拿大_5GRYV7"
      - "🇸🇪 瑞典_TF5CKT"
      - "🇰🇿 哈萨克斯坦_2GL0D7"
  - name: 🌍 国外媒体
    type: select
    proxies:
      - "🚀 节点选择"
      - "♻️ 自动选择"
      - "🎯 全球直连"
      - 8元老牌专线机场：cczzuu.top
      - "🇭🇰 香港_VU7BAQ"
      - "🇨🇳 中国_PF5FOH"
      - "🇹🇼 台湾_9SG9SN"
      - "🇺🇸 美国_M9WO69"
      - "🇷🇴 罗马尼亚_A4MJMP"
      - "🇩🇪 德国_YAH87O"
      - "🇮🇩 印尼_CTBG80"
      - "🇳🇱 荷兰_1O3UBK"
      - "🇫🇷 法国_ALKKR7"
      - "🇱🇻 拉脱维亚_QFC71C"
      - "🇲🇩 摩尔多瓦_JS7XT7"
      - "🇧🇬 保加利亚_88LFF7"
      - "🇷🇸 塞尔维亚_6XQRNL"
      - "🇬🇧 英国_P3HTT7"
      - "🇨🇦 加拿大_5GRYV7"
      - "🇸🇪 瑞典_TF5CKT"
      - "🇰🇿 哈萨克斯坦_2GL0D7"
  - name: 📲 电报信息
    type: select
    proxies:
      - "🚀 节点选择"
      - "🎯 全球直连"
      - 8元老牌专线机场：cczzuu.top
      - "🇭🇰 香港_VU7BAQ"
      - "🇨🇳 中国_PF5FOH"
      - "🇹🇼 台湾_9SG9SN"
      - "🇺🇸 美国_M9WO69"
      - "🇷🇴 罗马尼亚_A4MJMP"
      - "🇩🇪 德国_YAH87O"
      - "🇮🇩 印尼_CTBG80"
      - "🇳🇱 荷兰_1O3UBK"
      - "🇫🇷 法国_ALKKR7"
      - "🇱🇻 拉脱维亚_QFC71C"
      - "🇲🇩 摩尔多瓦_JS7XT7"
      - "🇧🇬 保加利亚_88LFF7"
      - "🇷🇸 塞尔维亚_6XQRNL"
      - "🇬🇧 英国_P3HTT7"
      - "🇨🇦 加拿大_5GRYV7"
      - "🇸🇪 瑞典_TF5CKT"
      - "🇰🇿 哈萨克斯坦_2GL0D7"
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - "🎯 全球直连"
      - "🚀 节点选择"
      - 8元老牌专线机场：cczzuu.top
      - "🇭🇰 香港_VU7BAQ"
      - "🇨🇳 中国_PF5FOH"
      - "🇹🇼 台湾_9SG9SN"
      - "🇺🇸 美国_M9WO69"
      - "🇷🇴 罗马尼亚_A4MJMP"
      - "🇩🇪 德国_YAH87O"
      - "🇮🇩 印尼_CTBG80"
      - "🇳🇱 荷兰_1O3UBK"
      - "🇫🇷 法国_ALKKR7"
      - "🇱🇻 拉脱维亚_QFC71C"
      - "🇲🇩 摩尔多瓦_JS7XT7"
      - "🇧🇬 保加利亚_88LFF7"
      - "🇷🇸 塞尔维亚_6XQRNL"
      - "🇬🇧 英国_P3HTT7"
      - "🇨🇦 加拿大_5GRYV7"
      - "🇸🇪 瑞典_TF5CKT"
      - "🇰🇿 哈萨克斯坦_2GL0D7"
  - name: 🍎 苹果服务
    type: select
    proxies:
      - "🚀 节点选择"
      - "🎯 全球直连"
      - 8元老牌专线机场：cczzuu.top
      - "🇭🇰 香港_VU7BAQ"
      - "🇨🇳 中国_PF5FOH"
      - "🇹🇼 台湾_9SG9SN"
      - "🇺🇸 美国_M9WO69"
      - "🇷🇴 罗马尼亚_A4MJMP"
      - "🇩🇪 德国_YAH87O"
      - "🇮🇩 印尼_CTBG80"
      - "🇳🇱 荷兰_1O3UBK"
      - "🇫🇷 法国_ALKKR7"
      - "🇱🇻 拉脱维亚_QFC71C"
      - "🇲🇩 摩尔多瓦_JS7XT7"
      - "🇧🇬 保加利亚_88LFF7"
      - "🇷🇸 塞尔维亚_6XQRNL"
      - "🇬🇧 英国_P3HTT7"
      - "🇨🇦 加拿大_5GRYV7"
      - "🇸🇪 瑞典_TF5CKT"
      - "🇰🇿 哈萨克斯坦_2GL0D7"
  - name: 📢 谷歌FCM
    type: select
    proxies:
      - "🚀 节点选择"
      - "🎯 全球直连"
      - "♻️ 自动选择"
      - 8元老牌专线机场：cczzuu.top
      - "🇭🇰 香港_VU7BAQ"
      - "🇨🇳 中国_PF5FOH"
      - "🇹🇼 台湾_9SG9SN"
      - "🇺🇸 美国_M9WO69"
      - "🇷🇴 罗马尼亚_A4MJMP"
      - "🇩🇪 德国_YAH87O"
      - "🇮🇩 印尼_CTBG80"
      - "🇳🇱 荷兰_1O3UBK"
      - "🇫🇷 法国_ALKKR7"
      - "🇱🇻 拉脱维亚_QFC71C"
      - "🇲🇩 摩尔多瓦_JS7XT7"
      - "🇧🇬 保加利亚_88LFF7"
      - "🇷🇸 塞尔维亚_6XQRNL"
      - "🇬🇧 英国_P3HTT7"
      - "🇨🇦 加拿大_5GRYV7"
      - "🇸🇪 瑞典_TF5CKT"
      - "🇰🇿 哈萨克斯坦_2GL0D7"
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - "🚀 节点选择"
      - "♻️ 自动选择"
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - "🚀 节点选择"
      - "🎯 全球直连"
      - "♻️ 自动选择"
      - 8元老牌专线机场：cczzuu.top
      - "🇭🇰 香港_VU7BAQ"
      - "🇨🇳 中国_PF5FOH"
      - "🇹🇼 台湾_9SG9SN"
      - "🇺🇸 美国_M9WO69"
      - "🇷🇴 罗马尼亚_A4MJMP"
      - "🇩🇪 德国_YAH87O"
      - "🇮🇩 印尼_CTBG80"
      - "🇳🇱 荷兰_1O3UBK"
      - "🇫🇷 法国_ALKKR7"
      - "🇱🇻 拉脱维亚_QFC71C"
      - "🇲🇩 摩尔多瓦_JS7XT7"
      - "🇧🇬 保加利亚_88LFF7"
      - "🇷🇸 塞尔维亚_6XQRNL"
      - "🇬🇧 英国_P3HTT7"
      - "🇨🇦 加拿大_5GRYV7"
      - "🇸🇪 瑞典_TF5CKT"
      - "🇰🇿 哈萨克斯坦_2GL0D7"

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,🚀 节点选择
  - RULE-SET,proxy,🚀 节点选择
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,🚀 节点选择
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🚀 节点选择
